initial commit

diff --git a/.github/workflows/aep-api-regression.yml b/.github/workflows/aep-api-regression.yml
--- a/.github/workflows/aep-api-regression.yml
+++ b/.github/workflows/aep-api-regression.yml
@@ -265,6 +265,7 @@ jobs:
       # ----------------------------------------
       # 10. Authenticate with Xray Cloud
       # ----------------------------------------
+      
       - name: Authenticate with Xray Cloud
         if: always()
         id: xray-auth
@@ -287,6 +288,33 @@ jobs:
       
       
       # ----------------------------------------
+      # Check Xray JUnit file
+      # ----------------------------------------    
+      
+      - name: Check Xray JUnit file
+        if: always()
+        shell: bash
+        run: |
+          echo "=== Current directory ==="
+          pwd
+
+          echo "=== Files ==="
+          ls -la
+
+          echo "=== JUnit file ==="
+          if [ -f "test-results.xml" ]; then
+            echo "test-results.xml exists"
+            ls -lh test-results.xml
+            echo "=== Contents ==="
+            cat test-results.xml
+          else
+            echo "ERROR: test-results.xml does not exist"
+            exit 1
+          fi
+
+      
+      
+      # ----------------------------------------
       # 11. Publish the Results to Xray
       # ----------------------------------------
 
@@ -295,11 +323,15 @@ jobs:
         shell: bash
         run: |
 
-          RESPONSE=$(curl -s \
+         echo "=== Xray JUnit file check ==="
+         pwd
+         ls -lh test-results.xml
+
+         RESPONSE=$(curl -s \
            --fail-with-body \
            -H "Authorization: Bearer $XRAY_TOKEN" \
            -H "Content-Type: text/xml" \
-           --data @"test-results.xml" \
+           --data-binary "@$(pwd)/"test-results.xml" \
            "https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=${{ secrets.XRAY_PROJECT_KEY }}"
           )
 
